---
- hosts: all
  vars:
    proxy_host: "agent.proxcet.io:443"

    manual_url_64: "https://misc.proxcet.io/proxy/bin/network-agent-amd64.tar.gz"
    manual_url_arm_64: "https://misc.proxcet.io/proxy/bin/network-agent-arm64.tar.gz"

    network_agent_config: "./config/network-agent/config.yaml"
    network_agent_service: "./config/network-agent/network-agent.service"
  tasks:
    - name: Enable IPv4 forwarding in sysctl
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#?net.ipv4.ip_forward='
        line: 'net.ipv4.ip_forward=1'
        validate: '/sbin/sysctl -p %s'
      become: yes

    - name: Enable IPv6 forwarding in sysctl
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#?net.ipv6.conf.all.forwarding='
        line: 'net.ipv6.conf.all.forwarding=1'
        validate: '/sbin/sysctl -p %s'
      become: yes

    - name: Apply sysctl changes
      ansible.builtin.command:
        cmd: /sbin/sysctl -p
      become: yes

    - name: Gather OS fact
      setup:
        filter: ansible_distribution

    - name: Detect architecture
      ansible.builtin.command: uname -m
      register: arch

    - name: Set architecture URL (x86_64)
      set_fact:
        arch_url: "{{ manual_url_64 }}"
      when: arch.stdout == "x86_64"

    - name: Set architecture URL (armv7)
      set_fact:
        arch_url: "{{ manual_url_arm }}"
      when: arch.stdout == "armv7"

    - name: Set architecture URL (aarch64)
      set_fact:
        arch_url: "{{ manual_url_arm_64 }}"
      when: arch.stdout == "aarch64"

    - name: Download agent
      ansible.builtin.get_url:
        url: "{{ arch_url }}"
        dest: "/tmp/network-agent.tar.gz"

    - name: Extract agent
      ansible.builtin.unarchive:
        src: "/tmp/network-agent.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move agent binary to destination
      ansible.builtin.command: mv /tmp/network-agent /usr/sbin/network-agent
      become: yes

    - name: Add binary to systemctl
      ansible.builtin.template:
        src: "{{ network_agent_service }}"
        dest: "/etc/systemd/system/network-agent.service"
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: Ensure /etc/network-agent directory exists
      ansible.builtin.file:
        path: /etc/network-agent
        state: directory
        owner: root
        group: root
        mode: 0755
      become: yes

    - name: Configure network-agent
      ansible.builtin.template:
        src: "{{ network_agent_config }}"
        dest: "/etc/network-agent/config.yaml"
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: Enable and start service
      ansible.builtin.systemd:
        name: network-agent
        enabled: yes
        state: started
      become: yes

    - name: Restart service
      ansible.builtin.systemd:
        name: network-agent
        state: restarted
      become: yes
